<?php 

$config = [
    'MODEL_PATH' => APPLICATION_PATH . DIRECTORY_SEPARATOR . 'model' . DIRECTORY_SEPARATOR,
    'VIEW_PATH' => APPLICATION_PATH . DIRECTORY_SEPARATOR . 'view' . DIRECTORY_SEPARATOR,
    'LIB_PATH' => APPLICATION_PATH . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR,
];

require $config['LIB_PATH'] . 'functions.php';